# PLUGINS #
source "%val{config}/packages.kak"

# COMMANDS #
source "%val{config}/commands.kak"

# KEYBINDS #
source "%val{config}/keybinds.kak"

# CONFIGURATION #
colorscheme 'vivendi'

hook global BufCreate ^[^*]+$ %{ add-highlighter buffer/ number-lines -separator ' ' }

set-option global indentwidth          2
set-option global tabstop              2
set-option global scrolloff            4,12
set-option global startup_info_version %sh{ date +%Y0101 }
set-option global ui_options           terminal_assistant=off
set-option global modelinefmt          '[{{mode_info}}] %sh{ echo $kak_buffile | sed "s/${HOME//\//\\/}/~/g" } {{context_info}}[%val{cursor_line} : %val{cursor_char_column}]%sh{ [ -n "$kak_opt_filetype" ] && echo "[$kak_opt_filetype]" }'
set-option global grepcmd              'rg --vimgrep'
